name: Tests

on:
  push:
    branches: [ master, kyleprice/standUpCI ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: g++ version
      run: |
        sudo apt install g++-9
        g++ --version
    # - name: run cmake
    #   run: cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLE=ON -DBUILD_TESTS=ON
        
    # - name: build
    #   run: cmake --build build
      
    # - name: test
    #   run: ./build/test/test_runner
