name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make build directory
      run: |
        mkdir build
        cd build
      
    - name: print dir
      run: |
        pwd
        ls
        cd ..
        ls
        pwd
#     - name: run cmake
#       run: cmake -DBUILD_TESTS=ON ..
      
#     - name: make
#       run: make
      
#     - name: run tests
#       run: ./test/test_runner
